services:
  emqx:
    image: emqx/emqx:5.5.0
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"     # MQTT
      - "8883:8883"     # MQTT over TLS
      - "8083:8083"     # WebSocket MQTT
      - "18083:18083"   # Dashboard UI
    environment:
      - EMQX_NODE__NAME=emqx@emqx
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_NODE__COOKIE=emqxsecretcookie

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

